### PR TITLE
Add hg38 init scripts

### PR DESCRIPTION
**Pull request by inodb**
Fix https://github.com/cBioPortal/cbioportal/issues/7641

### CODE REVIEW

**Comment by inodb** [comment]
Gonna merge this, b/c some user was asking about it and not sure how familiar they are with cloning a separate branch. But feel free to comment and I'll address any issues in a follow up PR

**Comment by SRodenburg** [comment]
Would it not make more sense to add hg38 as a CLI argument to `init.sh`?

**Comment by inodb** [comment]
@SRodenburg thanks for reviewing! Yeah that prolly makes more sense. This was a bit of a hackjob. We also still need to add hg38 data to datahub for actually loading some 38 data so will update that once we have that

**Comment by NikdAK** [comment]
Thanks for fixing the error mutation_event error and including hg38 to docker-compose! It seems to be running without problems.

Not sure if this is even a problem, but for the record: you have cbioportal:3.4.4 hard-coded in /config/init.sh 

Also, will simply modifying the data/init.sh work for mouse or are there some internal settings for human? 
The init_mm10 could look like this:

wget -O cgds.sql "https://raw.githubusercontent.com/cBioPortal/cbioportal/v1.7.3/db-scripts/src/main/resources/cgds.sql" && wget -O seed.sql.gz "https://github.com/cBioPortal/datahub/blob/master/seedDB_mouse/seed-cbioportal_mm10_v2.3.1.sql.gz"

**Comment by inodb** [comment]
@NikdAK good catch re hard coding of the version in `/config/init.sh`

For mouse I think that should work

Do note that the mutations tab relies a lot on Genome Nexus. We only have a human based version publicly available, so ideally one would also set up a mouse genome nexus instance: https://github.com/genome-nexus/genome-nexus

**Pull request merged**
